-- Trader psychology profile (one per user, evolves over time)
CREATE TABLE trader_profile (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL UNIQUE,
  
  -- Self-assessment (filled by user on first coach session)
  trading_style VARCHAR(20) CHECK (trading_style IN ('scalper', 'day_trader', 'swing_trader', 'position_trader')),
  risk_personality VARCHAR(20) CHECK (risk_personality IN ('aggressive', 'moderate', 'conservative')),
  experience_months INTEGER,
  primary_pairs TEXT[], -- e.g., {"EUR/USD", "GBP/USD"}
  trading_goals TEXT, -- free text: what they want to achieve
  
  -- AI-observed traits (updated by Manouk after sessions)
  observed_strengths JSONB DEFAULT '[]', 
  -- e.g., ["Good at identifying support/resistance", "Disciplined with stop losses"]
  observed_weaknesses JSONB DEFAULT '[]',
  -- e.g., ["Revenge trades after losses", "Cuts winners early", "Ignores MACD signals"]
  emotional_triggers JSONB DEFAULT '[]',
  -- e.g., ["Increases size after winning streak", "Trades impulsively during news events"]
  current_focus TEXT, -- what Manouk told them to work on
  personality_notes TEXT, -- free-form AI observations about the trader
  
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE trader_profile ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users access own profile" ON trader_profile FOR ALL USING (auth.uid() = user_id);

-- Coaching memory (summary of each session, persists across conversations)
CREATE TABLE coaching_memory (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  session_id UUID REFERENCES ai_coaching_sessions(id),
  
  -- Structured summary generated by Manouk at end of each session
  session_date TIMESTAMPTZ DEFAULT NOW(),
  session_type VARCHAR(20) NOT NULL, -- 'review', 'pre_trade', 'general'
  key_topics TEXT[], -- e.g., {"revenge trading", "EUR/USD analysis", "risk management"}
  advice_given TEXT NOT NULL, -- summary of what Manouk recommended
  commitments TEXT[], -- what the trader said they'd do
  -- e.g., {"Stop trading EUR/USD for 1 week", "Wait for RSI confirmation before entry"}
  follow_up_needed BOOLEAN DEFAULT FALSE,
  follow_up_note TEXT, -- what to check next session
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE coaching_memory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users access own memory" ON coaching_memory FOR ALL USING (auth.uid() = user_id);

-- Behavioral analysis snapshots (regenerated periodically)
CREATE TABLE behavioral_analysis (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) NOT NULL,
  
  -- When this analysis covers
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,
  trade_count INTEGER NOT NULL,
  
  -- Performance patterns
  win_rate_by_pair JSONB, -- {"EUR/USD": 35, "GBP/USD": 52}
  win_rate_by_day JSONB, -- {"monday": 45, "tuesday": 60, ...}
  win_rate_by_hour JSONB, -- {"09": 55, "14": 40, ...}
  win_rate_by_strategy JSONB, -- {"Pivot Rejection": 60, "Breakout": 35}
  avg_hold_winners_minutes INTEGER,
  avg_hold_losers_minutes INTEGER,
  
  -- Behavioral flags
  revenge_trade_count INTEGER DEFAULT 0, -- trade within 30 min of loss with larger size
  early_exit_count INTEGER DEFAULT 0, -- closed before TP with profit (cut winners)
  late_exit_count INTEGER DEFAULT 0, -- moved SL or held past SL (let losers run)
  rule_violation_attempts INTEGER DEFAULT 0, -- blocked by risk engine
  overtrading_days INTEGER DEFAULT 0, -- days with more than max_open_trades attempts
  
  -- Risk behavior
  avg_risk_percent DECIMAL(4,2), -- average risk % per trade
  max_risk_percent DECIMAL(4,2), -- highest risk % taken
  avg_rr_planned DECIMAL(4,2), -- average planned R:R
  avg_rr_actual DECIMAL(4,2), -- average actual R:R (did they hold to TP?)
  
  -- Strategy compliance
  strategy_logged_percent DECIMAL(4,1), -- % of trades with strategy notes
  screenshots_logged_percent DECIMAL(4,1), -- % of trades with screenshots
  template_usage JSONB, -- which templates used and how often
  
  -- Streak analysis
  longest_win_streak INTEGER,
  longest_loss_streak INTEGER,
  behavior_after_3_losses JSONB, -- {"increased_size": 2, "normal_size": 5, "stopped_trading": 3}
  behavior_after_3_wins JSONB,
  
  generated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE behavioral_analysis ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users access own analysis" ON behavioral_analysis FOR ALL USING (auth.uid() = user_id);
